# Generated by Django 4.2.13 on 2024-07-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="item_images"),
                ),
                ("price", models.FloatField()),
                ("discount_price", models.FloatField(blank="True", null="True")),
                ("slug", models.SlugField()),
                ("description", models.TextField()),
            ],
        ),
    ]
