# Generated by Django 4.2.13 on 2024-07-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eccommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "All"),
                    ("S", "Shoes"),
                    ("E", "Electronics"),
                    ("B", "Bags"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
