# Generated by Django 4.2.13 on 2024-07-28 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eccommerce", "0002_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eccommerce.billingaddress",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="eccommerce.payment",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "All"),
                    ("S", "Shoes"),
                    ("E", "Electronics"),
                    ("B", "Bags"),
                    ("C", "Clothes"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
