# Generated by Django 4.2.13 on 2024-07-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eccommerce", "0006_alter_billingaddress_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="additional_image",
            field=models.ImageField(blank=True, null=True, upload_to="item_images/"),
        ),
        migrations.AddField(
            model_name="product",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
    ]
